environment      = "dvp"
location         = "North Europe"
project_name     = "ncaproject"
ad_admin_group   = "az-developers-dvp"
sql_admin_user   = "sa_poc_test"
developers_group = "grp-developers-dvp"
